### ISSUE TITLE
Illumination Invariance

### ISSUE THREAD

**Issue by eric-czech** [hammerlab/celldom#50]
A recent experiment from Jeff showed much dimmer images, and this may have lead to some poor classifications:

<img width="962" alt="ic" src="https://user-images.githubusercontent.com/6130352/48476145-40b8d600-e7cc-11e8-9ac8-85104b383b06.png">

Solutions:
- More augmentation
- Normalization
    - A simple scheme like in [this paper](https://www.nature.com/articles/s41598-017-07599-6) would probably work well (min/max scale, subtract median)
    - It is probably worth doing https://github.com/hammerlab/celldom/issues/49 first before deciding this

**Comment by jmotschman** [comment]
For record keeping:
Can occur within a single experiment. Despite same microscope, camera, illumination settings (exposure time), and chip holder, etc.
Example below of 20181215-MV411 on Day 2 vs Day 3.
Also need to pinpoint and reduce this from happening on the hardware end. @benjaminyellen 

![illumination variation](https://user-images.githubusercontent.com/39501492/50173217-cac0f680-02c4-11e9-8cfa-70e3a3e511e1.png)

**Comment by jmotschman** [comment]
SmartScope v2.0 and the new Thor Labs LED minimizes this issue.
We can re-open this later if needed.

**Comment by jmotschman** [comment]
We also control the microscope LED brightness now directly with SmartScope v2.0 @calebsanfo 
In the future, if we notice any additional misclassification in the cell counts, the LED and microscope settings are easy to locate (in SmartScope).
Keeping this closed for now.
